### ISSUE TITLE
node-gyp rebuild failing

### ISSUE THREAD

**Issue by ChrisAitken** [Mowje/node-cryptopp#6]
I have been having issues installing OSx yosemite node-gyp is failing from both `npm i cryptopp` and `npm install git+https://github.com/Mowje/node-cryptopp.git.`

The message I get from node-gyp is : 

``` 
fs.js:439
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'osx13-binding.gyp'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at Object.<anonymous> (/Users/Chris/Developer/passage-proc/node_modules/cryptopp/prepareBuild.js:17:37)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
make: *** [lib] Error 8
```

node version - 0.10.37
node-gyp - 1.0.2
npm 2.6.0

**Comment by BatikhSouri** [comment]
Okay. #5 is related to that. I think I know what's causing it. Gonna work on it.

**Comment by BatikhSouri** [comment]
It should be fixed now. Can please retry and confirm?

**Comment by ChrisAitken** [comment]
It is working when rebuilding from source but when it comes to running from npm, node-gyp is still failing with the same error

**Comment by BatikhSouri** [comment]
As I've said in the README, at some point in the development of this module, I've been having issues with publishing it on npm. Hence the version on npm is outdated. Please only build from source until I get this fixed (and remove the note from the README).
